### PR TITLE
add dependabot and github-ci

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by xoreaxlmbdx** [comment]
hello, i'm not very familiar with github ci, so i have some questions.
1. where i can download executables that were built in rust.yml?
2. also, why there is a "build cfltk" step in rust.yml? why build cftlk manually? (i dont see step like this in [fltk-rs file](https://github.com/fltk-rs/fltk-rs/blob/master/.github/workflows/rust.yml) which is using to build examples).

Thanks.

**Comment by theavege** [comment]
[FYI](https://github.com/CM-IV/crypto_rs/pull/2#issuecomment-2403377887)

**Comment by theavege** [comment]
image

**Comment by theavege** [comment]
If it's not a secret, why the PR was rejected?

**Comment by xoreaxlmbdx** [comment]
because i dont need ci for it

**Pull request closed without merging**
